spring:
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:30032/hotel_db?currentSchema=hotel
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 500000
      maximum-pool-size: 10000
      idle-timeout: 600000             # 1 минута
      max-lifetime: 3000000
  liquibase:
    enabled: true
    change-log: classpath:/changelog.yml
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:30032/hotel_db?currentSchema=hotel
    default-schema: hotel
    liquibase-schema: hotel
    parameters:
      defaultSchemaName: hotel