version: '3.8'


services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_db
    command: >
      postgres -c max_connections=10000
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge

volumes:
  postgres-data: