apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "hotel_db"
          args:
            - "-c"
            - "max_connections=200"
            - "-c"
            - "shared_buffers=256MB"
            - "-c"
            - "effective_cache_size=1GB"
            - "-c"
            - "max_parallel_workers=4"
            - "-c"
            - "idle_in_transaction_session_timeout=60000"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432          # порт внутри кластера
      targetPort: 5432    # порт контейнера Postgres
      nodePort: 30032     # внешний порт (от 30000 до 32767)
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


## Создаем PostgreSQL
#  kubectl apply -f postgres.yaml
#
#  # Создаем приложение
#  kubectl apply -f deployment.yaml
#
#  # Проверяем статус
#  kubectl get pods
#  kubectl get services

## Проверим, что pod удален
#  kubectl get pods
#  kubectl get deployments
#  # или сокращенно
#  kubectl get deploy
#
#  # Удаляем deployment
#  kubectl delete deployment имя-деплоймента
#
#  # Пример:
#  kubectl delete deployment hotel-app

#  kubectl delete pvc postgres-pvc