name: reserved-hotel-db-service.yml
on:
  push:
    branches:
      - master
#    pull_request:
#      branches:
#        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Шаг 3: Сборка и тестирование проекта с помощью Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t skydiverkhv/db_service:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push skydiverkhv/db_service:latest
